apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Test v1beta3 Template
  description: A template for testing v1beta3 functionality
spec:
  owner: user:saikumarpaide
  type: library
  parameters:
    - title: Component Details
      required:
        - name
      properties:
        name:
          title: Component Name
          type: string
          description: Name of the component to create
    - title: Repository Details
      properties:
        repoSlug:
          title: GitHub Repository Slug
          type: string
          description: GitHub repository slug (e.g., owner/repo)
          default: saikumarpaide/test-repo
  steps:
    - id: log-message
      name: Log a message
      action: debug:log
      input:
        message: "Created component ${parameters.name} for repo ${parameters.repoSlug}"
